Ol4..Ol4
create database bankAcc;
CREATE TABLE BANKACC(                               
   ID INT PRIMARY KEY,                              
   NAME CHAR(10) NOT NULL,                           
   LAST_NAME CHAR(10) NOT NULL,                      
   START_BILL DATE,                                  
   START_T_BILL TIME,                                
   BALANCE DOUBLE NOT NULL,                          
   )ENGINE InnoDB DEFAULT CHARSET = UTF8;                

 CREATE TABLE TRANSACT(                              
   ID INTEGER NOT NULL,                              
   TRANSACTIONS DOUBLE NOT NULL,                     
   DATA_TRANS DATE,                                  
   TIME_TRANS TIME,                                  
   FOREIGN KEY(ID)                                   
    REFERENCES BANKACC(ID) ON DELETE CASCADE
	)ENGINE InnoDB DEFAULT CHARSET = UTF8;
	
DROP TRIGGER IF EXISTS TDATAINSERT; 	
DELIMITER $$
	CREATE TRIGGER TDATAINSERT BEFORE INSERT ON BANKACC
 FOR EACH ROW
BEGIN
 SET NEW.START_BILL = CURDATE(),
 NEW.START_T_BILL = CURTIME();
 END $$ DELIMITER;
 
 DELIMITER $$
 CREATE TRIGGER TDATAUPDATE BEFORE INSERT ON TRANSACT
 FOR EACH ROW
BEGIN  
 SET NEW.DATA_TRANS = CURDATE(),
 NEW.TIME_TRANS = CURTIME();
  END $$ DELIMITER;
  
  
  /*
  DROP TRIGGER IF EXISTS TACCINSERT;
  DELIMITER $$
  CREATE TRIGGER TACCINSERT AFTER INSERT ON BANKACC
 FOR EACH ROW
 BEGIN
 INSERT INTO TRANSACT VALUES(NEW.ID,NEW.BALANCE,CURDATE(),
 CURTIME());
   END $$ DELIMITER;
   */
   
   
   
 DELIMITER $$
  CREATE TRIGGER TTRANINSERT AFTER INSERT ON TRANSACT
 FOR EACH ROW
  BEGIN
 UPDATE BANKACC
  SET BALANCE = BALANCE + NEW.TRANSACTIONS
  WHERE BANKACC.ID=NEW.ID;
 END $$ DELIMITER;
 
 INSERT INTO BANKACC(ID,NAME,LAST_NAME,BALANCE) VALUES(200,'EGOR','KIRILLOV',0);
  
  
INSERT INTO TRANSACT(ID,TRANSACTIONS) VALUES(200,100);